# Comment that will be sent if an issue is judged to be closed.
comment: "This issue is closed because it does not meet our issue template. Please read it and fill all sections. You can also refer https://docs.taiko.dev/contributing/#reporting-an-issue"
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# Example 1: bug report
  - "Describe the bug"
  - "To Reproduce"
  - "Logs"
  - "Versions"
- content:
# Example 2: feature request
  - "Motivation / Use Case"
  - "Expected Behavior"
  - "Other Information"
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: false
# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
label: "needs-more-info"
# The bot will ignore any issues that are opened or reopened by the user names in exception
exception:
  - "BugDiver"
  - "NivedhaSenthil"
  - "saikrishna321"
  - "sriv"
  - "zabil"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
